labels_map = {
    0: "Animal: Cat / Breed: Abyssinian",
    1: "Animal: Cat / Breed: Bengal",
    2: "Animal: Cat / Breed: Birman",
    3: "Animal: Cat / Breed: Bombay",
    4: "Animal: Cat / Breed: British Shorthair",
    5: "Animal: Cat / Breed: Egyptian Mau",
    6: "Animal: Cat / Breed: Maine Coon",
    7: "Animal: Cat / Breed: Persian",
    8: "Animal: Cat / Breed: Ragdoll",
    9: "Animal: Cat / Breed: Russian Blue",
    10: "Animal: Cat / Breed: Siamese",
    11: "Animal: Cat / Breed: Sphynx",
    12: "Animal: Dog / Breed: American Bulldog",
    13: "Animal: Dog / Breed: American Pit Bull Terrier",
    14: "Animal: Dog / Breed: Basset Hound",
    15: "Animal: Dog / Breed: Beagle",
    16: "Animal: Dog / Breed: Boxer",
    17: "Animal: Dog / Breed: Chihuahua",
    18: "Animal: Dog / Breed: English Cocker Spaniel",
    19: "Animal: Dog / Breed: English Setter",
    20: "Animal: Dog / Breed: German Shorthaired",
    21: "Animal: Dog / Breed: Great Pyrenees",
    22: "Animal: Dog / Breed: Havanese",
    23: "Animal: Dog / Breed: Japanese Chin",
    24: "Animal: Dog / Breed: Keeshond",
    25: "Animal: Dog / Breed: Leonberger",
    26: "Animal: Dog / Breed: Miniature Pinscher",
    27: "Animal: Dog / Breed: Newfoundland",
    28: "Animal: Dog / Breed: Pomeranian",
    29: "Animal: Dog / Breed: Pug",
    30: "Animal: Dog / Breed: Saint Bernard",
    31: "Animal: Dog / Breed: Samoyed",
    32: "Animal: Dog / Breed: Scottish Terrier",
    33: "Animal: Dog / Breed: Shiba Inu",
    34: "Animal: Dog / Breed: Staffordshire Bull Terrier",
    35: "Animal: Dog / Breed: Wheaten Terrier",
    36: "Animal: Dog / Breed: Yorkshire Terrier"
}